"""
Market research and analyst reports model.
"""

from datetime import datetime

from sqlalchemy import INTEGER, TEXT, TIMESTAMP, VARCHAR, func
from sqlalchemy.orm import Mapped, mapped_column
from typing import Optional

from .base import Base


class MarketResearch(Base):
    """
    Market research and analyst reports with impact analysis.

    This table stores research articles, analyst reports, and industry publications
    focused on cocoa markets. Impact synthesis generated by OpenAI summarization.
    Updated daily at 10:30 PM via Make.com automation.

    Source: BIBLIO_ALL sheet from Excel file
    """

    __tablename__ = "market_research"

    id: Mapped[int] = mapped_column(INTEGER, primary_key=True, autoincrement=True)
    date: Mapped[datetime] = mapped_column(
        TIMESTAMP,
        nullable=False,
        index=True,
        comment="Publication or analysis date of the research",
    )
    author: Mapped[str] = mapped_column(
        VARCHAR(100),
        nullable=False,
        comment="Author or source of the research/publication",
    )
    summary: Mapped[str] = mapped_column(
        TEXT, nullable=False, comment="Summary or abstract of the research content"
    )
    keywords: Mapped[Optional[str]] = mapped_column(
        TEXT, comment="Keywords or tags associated with this research"
    )
    impact_synthesis: Mapped[str] = mapped_column(
        TEXT,
        nullable=False,
        comment="Synthesized market impact assessment - how this research affects trading decisions",
    )
    date_text: Mapped[str] = mapped_column(
        VARCHAR(100),
        nullable=False,
        comment="Date in text format (might include additional context like 'Q1 2024')",
    )

    # === AUDIT FIELDS ===
    created_at: Mapped[datetime] = mapped_column(TIMESTAMP, server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(
        TIMESTAMP, server_default=func.now(), onupdate=func.now()
    )
