"""
Weather and agricultural conditions model.
"""

from datetime import datetime

from sqlalchemy import INTEGER, TEXT, TIMESTAMP, VARCHAR, func
from sqlalchemy.orm import Mapped, mapped_column

from .base import Base


class WeatherData(Base):
    """
    Weather and agricultural conditions affecting cocoa markets.

    This table stores weather reports and agricultural conditions from Ghana and
    Côte d'Ivoire (10 locations) that impact cocoa prices. Updated daily at 10:30 PM
    via Make.com automation. Impact analysis generated by OpenAI.

    Source: METEO_ALL sheet from Excel file
    """

    __tablename__ = "weather_data"

    id: Mapped[int] = mapped_column(INTEGER, primary_key=True, autoincrement=True)
    date: Mapped[datetime] = mapped_column(
        TIMESTAMP,
        nullable=False,
        index=True,
        comment="Date of the weather report or agricultural update",
    )
    text: Mapped[str] = mapped_column(
        TEXT, nullable=False, comment="Full text of the weather/agricultural report"
    )
    summary: Mapped[str] = mapped_column(
        TEXT, nullable=False, comment="Summary of key weather/agricultural conditions"
    )
    keywords: Mapped[str] = mapped_column(
        VARCHAR(500),
        nullable=False,
        comment="Keywords describing weather conditions, crop types, regions affected",
    )
    impact_synthesis: Mapped[str] = mapped_column(
        TEXT,
        nullable=False,
        comment="Synthesized market impact - how weather conditions affect commodity prices",
    )

    # === AUDIT FIELDS ===
    created_at: Mapped[datetime] = mapped_column(TIMESTAMP, server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(
        TIMESTAMP, server_default=func.now(), onupdate=func.now()
    )
