[build]
builder = "DOCKERFILE"
dockerfilePath = "backend/Dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Cron job for daily data import at 9PM Paris time
[[services]]
name = "data-import-cron"
cron = "15 23 * * *"
command = "poetry run import"
timeZone = "Europe/Paris"
