"""Update score fields to DECIMAL(8,2)

Revision ID: 45cf4bc63dfc
Revises: 449f56ae2867
Create Date: 2025-08-03 19:53:43.838162

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "45cf4bc63dfc"
down_revision: Union[str, Sequence[str], None] = "449f56ae2867"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "indicator",
        "rsi_score",
        existing_type=sa.NUMERIC(precision=4, scale=2),
        type_=sa.DECIMAL(precision=8, scale=2),
        comment="Individual score for RSI indicator (extended range for actual data)",
        existing_comment="Individual score for RSI indicator (-6 to +6 scale)",
        existing_nullable=True,
    )
    op.alter_column(
        "indicator",
        "macd_score",
        existing_type=sa.NUMERIC(precision=4, scale=2),
        type_=sa.DECIMAL(precision=8, scale=2),
        comment="Individual score for MACD indicator (extended range for actual data)",
        existing_comment="Individual score for MACD indicator (-6 to +6 scale)",
        existing_nullable=True,
    )
    op.alter_column(
        "indicator",
        "stochastic_score",
        existing_type=sa.NUMERIC(precision=4, scale=2),
        type_=sa.DECIMAL(precision=8, scale=2),
        comment="Individual score for Stochastic oscillator (extended range for actual data)",
        existing_comment="Individual score for Stochastic oscillator (-6 to +6 scale)",
        existing_nullable=True,
    )
    op.alter_column(
        "indicator",
        "atr_score",
        existing_type=sa.NUMERIC(precision=4, scale=2),
        type_=sa.DECIMAL(precision=8, scale=2),
        comment="Individual score for ATR (volatility measure) (extended range for actual data)",
        existing_comment="Individual score for ATR (volatility measure) (-6 to +6 scale)",
        existing_nullable=True,
    )
    op.alter_column(
        "indicator",
        "macroeco_score",
        existing_type=sa.NUMERIC(precision=4, scale=2),
        type_=sa.DECIMAL(precision=8, scale=2),
        comment="OpenAI-generated macroeconomic score (extended range for actual data)",
        existing_comment="OpenAI-generated macroeconomic score: 0.9, 1.0, or 1.1",
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "indicator",
        "macroeco_score",
        existing_type=sa.DECIMAL(precision=8, scale=2),
        type_=sa.NUMERIC(precision=4, scale=2),
        comment="OpenAI-generated macroeconomic score: 0.9, 1.0, or 1.1",
        existing_comment="OpenAI-generated macroeconomic score (extended range for actual data)",
        existing_nullable=True,
    )
    op.alter_column(
        "indicator",
        "atr_score",
        existing_type=sa.DECIMAL(precision=8, scale=2),
        type_=sa.NUMERIC(precision=4, scale=2),
        comment="Individual score for ATR (volatility measure) (-6 to +6 scale)",
        existing_comment="Individual score for ATR (volatility measure) (extended range for actual data)",
        existing_nullable=True,
    )
    op.alter_column(
        "indicator",
        "stochastic_score",
        existing_type=sa.DECIMAL(precision=8, scale=2),
        type_=sa.NUMERIC(precision=4, scale=2),
        comment="Individual score for Stochastic oscillator (-6 to +6 scale)",
        existing_comment="Individual score for Stochastic oscillator (extended range for actual data)",
        existing_nullable=True,
    )
    op.alter_column(
        "indicator",
        "macd_score",
        existing_type=sa.DECIMAL(precision=8, scale=2),
        type_=sa.NUMERIC(precision=4, scale=2),
        comment="Individual score for MACD indicator (-6 to +6 scale)",
        existing_comment="Individual score for MACD indicator (extended range for actual data)",
        existing_nullable=True,
    )
    op.alter_column(
        "indicator",
        "rsi_score",
        existing_type=sa.DECIMAL(precision=8, scale=2),
        type_=sa.NUMERIC(precision=4, scale=2),
        comment="Individual score for RSI indicator (-6 to +6 scale)",
        existing_comment="Individual score for RSI indicator (extended range for actual data)",
        existing_nullable=True,
    )
    # ### end Alembic commands ###
